from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, IntegerField, SubmitField, PasswordField, DateField, SelectField, FloatField
from wtforms.validators import DataRequired, Email

class EstudianteForm(FlaskForm):
    cedula = IntegerField('Cedula', validators = [DataRequired()], render_kw = {"placeholder":"Cédula"})
    responsable = StringField('Responsable', validators = [DataRequired()], render_kw = {"placeholder":"Responsable"})
    curso = SelectField('Indique año y seccion a cursar', validators = [DataRequired()], choices = [('Indique año y seccion a cursar',0),(11,'1er año A'),(12,'1er año B'),(13,'1er año C'),(21,'2do año A'),(22,'2do año B'),(23,'2do año C'),(31,'3er año A'),(32,'3er año B'),(33,'3er año C')])
    tipo_inscrip = SelectField('Tipo de Inscripción', validators = [DataRequired()], choices = [('Tipo de Inscripción',0),('Regular','Regular'),('Nuevo Ingreso','Nuevo Ingreso')])
    antecedente_escolar = StringField('Antecedente Escolar', validators = [DataRequired()], render_kw = {"placeholder":"Antecedente Escolar"})
    nombres = StringField('Nombres', validators = [DataRequired()], render_kw = {"placeholder":"Nombres"})
    apellidos = StringField('Apellidos', validators = [DataRequired()], render_kw = {"placeholder":"Apellidos"})
    genero = SelectField('Género del estudiante', validators = [DataRequired()], choices = [('Género del estudiante',0),('Masculino','Masculino'),('Femenino','Femenino')])
    nacionalidad = SelectField('Nacionalidad', validators = [DataRequired()], choices = [('Nacionalidad',0),('Venezolano(a)','Venezolano(a)'),('Extranjero(a)','Extranjero(a)')])
    fecha_naci = DateField('Fecha de nacimiento', validators = [DataRequired()], format = '%Y-%m-%d')
    lugar_naci = StringField('Lugar de Nacimiento', validators = [DataRequired()], render_kw = {"placeholder":"Lugar de Nacimiento"})
    parto = SelectField('Parto simple o multiple', validators = [DataRequired()], choices = [('Parto simple o multiple',0),('Simple','Simple'),('Multiple','Multiple')])
    edad = IntegerField('Edad', validators = [DataRequired()], render_kw = {"placeholder":"Edad"})    
    lateralidad = SelectField('Lateralidad del estudiante', validators = [DataRequired()], choices = [('Lateralidad del estudiante',0),('zurdo','zurdo'),('diestro','diestro')])
    peso = FloatField('Peso', validators = [DataRequired()], render_kw = {"placeholder":"Peso en Kg"})
    estatura = FloatField('Estatura', validators = [DataRequired()], render_kw = {"placeholder":"Estatura en mtr"})
    hermanos = StringField('Posee hermanos?', validators = [DataRequired()], render_kw = {"placeholder":"Posee hermanos?"})
    hermanos_inst = StringField('Hermanos  en la Institución?', validators = [DataRequired()], render_kw = {"placeholder":"Hermanos  en la Institución?"})
    talla_camisa = SelectField('Talla de camisa', validators = [DataRequired()], choices = [('Talla de camisa',0),('M','M'),('L','L')])
    talla_pantalon = SelectField('Talla de pantalon', validators = [DataRequired()], choices = [('Talla de pantalon',0),('M','M'),('L','L')])
    salud = StringField('Estado de Salud', validators = [DataRequired()], render_kw = {"placeholder":"Estado de Salud"})
    covid = StringField('Padeció Covid?', validators = [DataRequired()], render_kw = {"placeholder":"Padeció Covid?"})
    vacunas_covid = SelectField('Vacunas aplicadas', validators = [DataRequired()], choices = [('Vacunas aplicadas',0),('1ra dosis','1ra dosis'),('2da dosis','2da dosis')])
    atencion_espec = StringField('Atención Especializada', validators = [DataRequired()], render_kw = {"placeholder":"Atención Especializada"})
    email_estud = EmailField('Correo del estudiante', validators = [DataRequired()], render_kw = {"placeholder":"Correo del estudiante"})
    equipo_tecn = SelectField('Equipos Tecnológicos', validators = [DataRequired()], choices = [('Equipos Tecnológicos',0),('telefono','telefono'),('pc','pc')])
    acceso_inter = SelectField('Acceso a Internet?', validators = [DataRequired()], choices = [('Acceso a Internet?',0),('si','si'),('no','no')])
    redes_soc = StringField('Redes Sociales', validators = [DataRequired()], render_kw = {"placeholder":"Redes Sociales"})
    canaima = SelectField('Posee canaima?', validators = [DataRequired()], choices = [('Posee canaima?',0),('si','si'),('no','no')])
    submit = SubmitField('Inscribir Estudiante')
