"""empty message

Revision ID: 080977524bcd
Revises: 40249f480b65
Create Date: 2023-03-05 15:38:35.315074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080977524bcd'
down_revision = '40249f480b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asigna', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ced_estudiante', sa.Integer(), nullable=False))
        batch_op.drop_constraint('asigna_cedula_estudiante_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'estudiante', ['ced_estudiante'], ['cedula'])
        batch_op.drop_column('cedula_estudiante')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asigna', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cedula_estudiante', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('asigna_cedula_estudiante_fkey', 'estudiante', ['cedula_estudiante'], ['cedula'])
        batch_op.drop_column('ced_estudiante')

    # ### end Alembic commands ###
