"""empty message

Revision ID: 093c13d36cf6
Revises: 6e6264bacd2e
Create Date: 2023-03-05 12:27:23.350473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093c13d36cf6'
down_revision = '6e6264bacd2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imparte',
    sa.Column('cod_imparte', sa.Integer(), nullable=False),
    sa.Column('cod_materia', sa.String(length=10), nullable=False),
    sa.Column('cod_grado_seccion', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['cod_grado_seccion'], ['grado_seccion.cod_grado_seccion'], ),
    sa.ForeignKeyConstraint(['cod_materia'], ['grado_seccion.cod_grado_seccion'], ),
    sa.PrimaryKeyConstraint('cod_imparte', 'cod_materia', 'cod_grado_seccion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imparte')
    # ### end Alembic commands ###
