"""empty message

Revision ID: 14119238385d
Revises: d20d57c90703
Create Date: 2023-02-18 19:10:17.943663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14119238385d'
down_revision = 'd20d57c90703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profesor',
    sa.Column('cedula_prof', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('materiaImparte', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('cedula_prof')
    )
    op.create_table('asigna',
    sa.Column('cod_asignar', sa.Integer(), nullable=False),
    sa.Column('cedula_estudiante', sa.Integer(), nullable=False),
    sa.Column('cedula_profesor', sa.Integer(), nullable=False),
    sa.Column('cod_grado_seccion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cedula_estudiante'], ['estudiante.cedula'], ),
    sa.ForeignKeyConstraint(['cedula_profesor'], ['profesor.cedula_prof'], ),
    sa.ForeignKeyConstraint(['cod_grado_seccion'], ['grado_seccion.cod_grado_seccion'], ),
    sa.PrimaryKeyConstraint('cod_asignar', 'cedula_estudiante', 'cedula_profesor', 'cod_grado_seccion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asigna')
    op.drop_table('profesor')
    # ### end Alembic commands ###
