"""empty message

Revision ID: 186e43e6cd8c
Revises: 8cf8e0e93c9f
Create Date: 2023-03-04 19:55:50.425128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186e43e6cd8c'
down_revision = '8cf8e0e93c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.alter_column('cod_materia',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('materia_cod_materia_seq'::regclass)"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.alter_column('cod_materia',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('materia_cod_materia_seq'::regclass)"))

    # ### end Alembic commands ###
