"""empty message

Revision ID: 41b1edb142fb
Revises: 0b81526f3c60
Create Date: 2023-01-27 23:34:33.901807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b1edb142fb'
down_revision = '0b81526f3c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.alter_column('representante_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.alter_column('representante_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
