"""empty message

Revision ID: 8de082295665
Revises: 0086a333b046
Create Date: 2023-03-06 21:25:34.717531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de082295665'
down_revision = '0086a333b046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imparte',
    sa.Column('cod_imparte', sa.Integer(), nullable=False),
    sa.Column('cod_materia', sa.String(length=10), nullable=False),
    sa.Column('cod_grado_seccion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_grado_seccion'], ['grado_seccion.cod_grado_seccion'], ),
    sa.ForeignKeyConstraint(['cod_materia'], ['materia.cod_materia'], ),
    sa.PrimaryKeyConstraint('cod_imparte', 'cod_materia', 'cod_grado_seccion')
    )
    op.create_table('nota',
    sa.Column('cod_nota', sa.Integer(), nullable=False),
    sa.Column('nota_1er_lapso', sa.Integer(), nullable=False),
    sa.Column('nota_2do_lapso', sa.Integer(), nullable=False),
    sa.Column('nota_3er_lapso', sa.Integer(), nullable=False),
    sa.Column('promedio', sa.Integer(), nullable=False),
    sa.Column('ced_estudiante', sa.Integer(), nullable=True),
    sa.Column('cod_materia', sa.String(length=10), nullable=True),
    sa.Column('cedula_prof', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ced_estudiante'], ['estudiante.cedula'], ),
    sa.ForeignKeyConstraint(['cedula_prof'], ['profesor.cedula_prof'], ),
    sa.ForeignKeyConstraint(['cod_materia'], ['materia.cod_materia'], ),
    sa.PrimaryKeyConstraint('cod_nota')
    )
    with op.batch_alter_table('asigna', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ced_estudiante', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cod_materia', sa.String(length=10), nullable=False))
        batch_op.drop_constraint('asigna_cedula_estudiante_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'estudiante', ['ced_estudiante'], ['cedula'])
        batch_op.create_foreign_key(None, 'materia', ['cod_materia'], ['cod_materia'])
        batch_op.drop_column('cedula_estudiante')

    with op.batch_alter_table('cursa', schema=None) as batch_op:
        batch_op.alter_column('cod_materia',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.alter_column('cod_materia',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('materia_cod_materia_seq'::regclass)"))

    with op.batch_alter_table('profesor', schema=None) as batch_op:
        batch_op.drop_column('materiaImparte')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profesor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materiaImparte', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.alter_column('cod_materia',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('materia_cod_materia_seq'::regclass)"))

    with op.batch_alter_table('cursa', schema=None) as batch_op:
        batch_op.alter_column('cod_materia',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('asigna', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cedula_estudiante', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('asigna_cedula_estudiante_fkey', 'estudiante', ['cedula_estudiante'], ['cedula'])
        batch_op.drop_column('cod_materia')
        batch_op.drop_column('ced_estudiante')

    op.drop_table('nota')
    op.drop_table('imparte')
    # ### end Alembic commands ###
