"""empty message

Revision ID: 8e29b71b6dc0
Revises: a59f6f52ec98
Create Date: 2023-03-04 20:19:31.894157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e29b71b6dc0'
down_revision = 'a59f6f52ec98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materia',
    sa.Column('cod_materia', sa.String(length=10), nullable=False),
    sa.Column('nom_materia', sa.String(length=50), nullable=False),
    sa.Column('cedula_prof', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cedula_prof'], ['profesor.cedula_prof'], ),
    sa.PrimaryKeyConstraint('cod_materia')
    )
    with op.batch_alter_table('asigna', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cod_materia', sa.String(length=10), nullable=False))
        batch_op.create_foreign_key(None, 'materia', ['cod_materia'], ['cod_materia'])

    with op.batch_alter_table('cursa', schema=None) as batch_op:
        batch_op.alter_column('cod_materia',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'materia', ['cod_materia'], ['cod_materia'])

    with op.batch_alter_table('nota', schema=None) as batch_op:
        batch_op.alter_column('cod_materia',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'materia', ['cod_materia'], ['cod_materia'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nota', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cod_materia',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('cursa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('cod_materia',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('asigna', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cod_materia')

    op.drop_table('materia')
    # ### end Alembic commands ###
