"""empty message

Revision ID: d158e391b25e
Revises: 
Create Date: 2023-01-26 22:30:19.537625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd158e391b25e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('representante',
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('apellido', sa.String(length=60), nullable=False),
    sa.Column('nacionalidad', sa.String(length=15), nullable=False),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('parentesco', sa.String(length=30), nullable=False),
    sa.Column('lugar_naci', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.BigInteger(), nullable=False),
    sa.Column('telefono_alt', sa.BigInteger(), nullable=False),
    sa.Column('profesion', sa.String(length=100), nullable=False),
    sa.Column('telefono_trab', sa.BigInteger(), nullable=False),
    sa.Column('direccion_trab', sa.String(length=200), nullable=False),
    sa.Column('vive_chacao', sa.String(length=10), nullable=False),
    sa.Column('direccion_dom', sa.String(length=200), nullable=False),
    sa.Column('estado_viv_infra', sa.String(length=100), nullable=False),
    sa.Column('estado_viv_tipo', sa.String(length=100), nullable=False),
    sa.Column('estado_viv_cond', sa.String(length=100), nullable=False),
    sa.Column('resolucion_0', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('cedula')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('names', sa.String(length=50), nullable=False),
    sa.Column('lastnames', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('estudiante',
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('responsable', sa.String(length=60), nullable=False),
    sa.Column('curso', sa.String(length=30), nullable=False),
    sa.Column('tipo_inscrip', sa.String(length=30), nullable=False),
    sa.Column('antecedente_escolar', sa.String(length=30), nullable=False),
    sa.Column('nombres', sa.String(length=60), nullable=False),
    sa.Column('apellidos', sa.String(length=60), nullable=False),
    sa.Column('genero', sa.String(length=15), nullable=False),
    sa.Column('nacionalidad', sa.String(length=15), nullable=False),
    sa.Column('fecha_naci', sa.Date(), nullable=False),
    sa.Column('parto', sa.String(length=200), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('lateralidad', sa.String(length=30), nullable=False),
    sa.Column('lugar_naci', sa.String(length=200), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('estatura', sa.Integer(), nullable=False),
    sa.Column('hermanos', sa.String(length=20), nullable=False),
    sa.Column('hermanos_inst', sa.String(length=20), nullable=False),
    sa.Column('talla_camisa', sa.String(length=10), nullable=False),
    sa.Column('talla_pantalon', sa.String(length=10), nullable=False),
    sa.Column('salud', sa.String(length=50), nullable=False),
    sa.Column('covid', sa.String(length=20), nullable=False),
    sa.Column('vacunas_covid', sa.String(length=50), nullable=False),
    sa.Column('atencion_espec', sa.String(length=50), nullable=False),
    sa.Column('email_estud', sa.String(length=254), nullable=False),
    sa.Column('equipo_tecn', sa.String(length=50), nullable=False),
    sa.Column('acceso_inter', sa.String(length=200), nullable=False),
    sa.Column('redes_soc', sa.String(length=200), nullable=False),
    sa.Column('canaima', sa.String(length=10), nullable=False),
    sa.Column('representante_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['representante_id'], ['representante.cedula'], ),
    sa.PrimaryKeyConstraint('cedula')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estudiante')
    op.drop_table('user')
    op.drop_table('representante')
    # ### end Alembic commands ###
