"""empty message

Revision ID: d8f54cd7c5b9
Revises: 080977524bcd
Create Date: 2023-03-05 19:26:48.646249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f54cd7c5b9'
down_revision = '080977524bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asigna',
    sa.Column('cod_asignar', sa.Integer(), nullable=False),
    sa.Column('ced_estudiante', sa.Integer(), nullable=False),
    sa.Column('cedula_prof', sa.Integer(), nullable=False),
    sa.Column('cod_grado_seccion', sa.Integer(), nullable=False),
    sa.Column('cod_materia', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['ced_estudiante'], ['estudiante.cedula'], ),
    sa.ForeignKeyConstraint(['cedula_prof'], ['profesor.cedula_prof'], ),
    sa.ForeignKeyConstraint(['cod_grado_seccion'], ['grado_seccion.cod_grado_seccion'], ),
    sa.ForeignKeyConstraint(['cod_materia'], ['materia.cod_materia'], ),
    sa.PrimaryKeyConstraint('cod_asignar', 'ced_estudiante', 'cedula_prof', 'cod_grado_seccion', 'cod_materia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asigna')
    # ### end Alembic commands ###
