"""empty message

Revision ID: d9903f0b1681
Revises: 1a9aca987652
Create Date: 2023-02-21 20:14:32.586513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9903f0b1681'
down_revision = '1a9aca987652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cod_materia', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'materia', ['cod_materia'], ['cod_materia'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cod_materia')

    # ### end Alembic commands ###
