"""empty message

Revision ID: fc1888b33fa4
Revises: 3f7b94a20bd9
Create Date: 2023-02-21 21:20:19.016564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1888b33fa4'
down_revision = '3f7b94a20bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.alter_column('cod_grado_seccion',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('grado_seccion', schema=None) as batch_op:
        batch_op.alter_column('cod_grado_seccion',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('grado_seccion_cod_grado_seccion_seq'::regclass)"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grado_seccion', schema=None) as batch_op:
        batch_op.alter_column('cod_grado_seccion',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('grado_seccion_cod_grado_seccion_seq'::regclass)"))

    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.alter_column('cod_grado_seccion',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
